apiVersion: v1
kind: PersistentVolume
metadata:
  name: nexus-pv-hostpath
  namespace: default
  labels:
    type: local
    label-name: nexus-data
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/.data/nexus"
