apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-pvc-hostpath
  namespace: default
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector: 
    matchLabels: 
      type: local
      label-name: nexus-data
