---
# tasks file for ssh_keypair_role

- name: Create target directory for key
  file: path="{{ key_folder }}" state=directory mode=0700 owner="{{ sudo_user }}" group="{{ sudo_user }}"

- name : Generate ssh keypair
  become_user: "{{ sudo_user }}"
  openssh_keypair:
    path: "{{ key_folder }}/{{ key_name }}"
    owner: "{{ sudo_user }}"
    group: "{{ sudo_user }}"


- name: Install sshpass
  yum:
    name: sshpass
    state: present
  become: yes

- name: Copy authorized keys to remote
  become_user: "{{ sudo_user }}"
  command: "sshpass -p  {{ ssh_password_of_nodes }} ssh-copy-id -i {{ key_folder }}/{{ key_name }}.pub {{ sudo_user }}@{{ item }} -o StrictHostKeyChecking=no"
  with_items: "{{ groups['nodes'] }}"

