---
# tasks file for user_setup_role

- name: Make sure we have a 'wheel' group
  group:
    name: wheel
    state: present

- name: Allow 'wheel' group to have passwordless sudo
  become: yes
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: visudo -cf %s

- name: Creating non root users
  become: yes
  user:
    name: "{{ item }}"
    password: "{{ upassword | password_hash('sha512') }}"
  #update_password: on_create
  with_items: "{{ sudoers }}"

- name: Add sudoers users to wheel group
  become: yes
  user:
    name: "{{ item }}"
    groups: wheel
    append: yes
  with_items: "{{ sudoers }}"
