---

- hosts:
    - nodes
    - rke
    - gitlab
    - nexus
  name: Play1 - Setup non-root users and set DNS entries
  remote_user: root
  vars:
    resolv_nameservers:
      - 8.8.8.8
    sudoers:
      - ananya
    upassword: password
  roles:
    - user_setup_role
    - dns_role

- hosts: nodes
  name:  Play2 - Configure prerequisites in k8 nodes
  vars:
    sudo_user: ananya
    kernel_modules_for_rke:
      - br_netfilter
      - ip6_udp_tunnel
      - ip_set
      - ip_set_hash_ip
      - ip_set_hash_net
      - iptable_filter
      - iptable_nat
      - iptable_mangle
      - iptable_raw
      - nf_conntrack_netlink
      - nf_conntrack
      - nf_conntrack_ipv4
      - nf_defrag_ipv4
      - nf_nat
      - nf_nat_ipv4
      - nf_nat_masquerade_ipv4
      - nfnetlink
      - udp_tunnel
      - veth
      - vxlan
      - x_tables
      - xt_addrtype
      - xt_conntrack
      - xt_comment
      - xt_mark
      - xt_multiport
      - xt_nat
      - xt_recent
      - xt_set
      - xt_statistic
      - xt_tcpudp
    firewall_ports:
      - 22/tcp
      - 80/tcp
      - 179/tcp
      - 443/tcp
      - 2376/tcp
      - 2379/tcp
      - 2380/tcp
      - 5543/tcp
      - 6443/tcp
      - 8472/udp
      - 9099/tcp
      - 10250/tcp
      - 10254/tcp
      - 10249/tcp
      - 30000-32767/tcp
      - 30000-32767/udp
  roles:
      - docker_role
      - kernels_role
      - networking_role

- hosts: rke
  name: Play3 - Configure passwordless ssh from RKE to other nodes, install docker, rke and helm
  vars:
    sudo_user: ananya
    key_folder: /home/ananya/.ssh
    key_name: id_rsa
    ssh_password_of_nodes: my_password
  roles:
      - docker_role
      - ssh_keypair_role
      - rke_role
      - helm_role

- hosts: gitlab
  name: Play4 - Install Jenkins and Gitlab
  vars:
    sudo_user: ananya
    sudoers:
      - ananya
    upassword: password
  roles:
    - user_setup_role
    - jenkins_role
    - gitlab_role

- hosts: nexus
  name: Play5 - Install Nexus
  vars:
    sudoers:
          - ananya
    sudo_user: ananya
  roles:
    - nexus_role