---
- hosts: 
    - nodes
    - rke
  name: play1
  remote_user: root
  vars:
    sudoers:
      - ananya
    upassword: password
  roles:
    - user_setup_role

- hosts: nodes
  name:  Play2
  vars:
    resolv_nameservers:
      - 8.8.8.8    
    sudo_user: ananya
    kernel_modules_for_rke:
      - br_netfilter
      - ip6_udp_tunnel
      - ip_set
      - ip_set_hash_ip
      - ip_set_hash_net
      - iptable_filter
      - iptable_nat
      - iptable_mangle
      - iptable_raw
      - nf_conntrack_netlink
      - nf_conntrack
      - nf_conntrack_ipv4
      - nf_defrag_ipv4
      - nf_nat
      - nf_nat_ipv4
      - nf_nat_masquerade_ipv4
      - nfnetlink
      - udp_tunnel
      - veth
      - vxlan
      - x_tables
      - xt_addrtype
      - xt_conntrack
      - xt_comment
      - xt_mark
      - xt_multiport
      - xt_nat
      - xt_recent
      - xt_set
      - xt_statistic
      - xt_tcpudp 
  roles:
      - dns_role
      - docker_role
      - kernels_role
      - networking_role

- hosts: rke
  name: Play3
  vars:
    sudo_user: ananya
    rancher_name: rancher_container
    rancher_port: 8000
    key_folder: /home/ananya/.ssh/id_rsa
    key_path: /home/ananya/.ssh/id_rsa.pub
  roles:
      - docker_role
#      - ssh_keypair_role
      - rke_role
