apiVersion: v1
kind: Service
metadata:
  name: kafka-service
spec:
  type: LoadBalancer
  externalIPs:
    - 10.203.0.6
  ports:
    - name: port-9092
      port: 9092
      protocol: TCP
  selector:
    app: kafka
