---
# tasks file for networking_role
- name: bridge-nf-call-iptables in systemctl
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: '1'
    sysctl_set: yes

- name: Install firewalld
  yum:
    name: firewalld
    state: latest
  ignore_errors: yes

- name: Start firewalld
  service:
    name: firewalld
    state: started
    enabled: False
  ignore_errors: yes

- name: Open require ports
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
  with_items: "{{ firewall_ports }}"
