---
# vars file for rke_role
rke:
  services:
    kube_api:
      service_cluster_ip_range: 10.43.0.0/16
      pod_security_policy: false
      always_pull_images: false
    kube_controller:
      cluster_cidr: 10.42.0.0/16
      service_cluster_ip_range: 10.43.0.0/16
    kubelet:
      cluster_domain: cluster.local
      cluster_dns_server: 10.43.0.10
      fail_swap_on: false
  network:
    plugin: calico
  authentication:
    strategy: x509
  ssh_key_path: "/home/ananya/.ssh/id_rsa"
  ssh_agent_auth: false
  authorization:
    mode: rbac
  ignore_docker_version: false
  kubernetes_version: "v1.13.5-rancher1-2"
  cluster_name: "demo_cluster"
  restore:
    restore: false
    snapshot_name: ""