--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: mysql
  name: mysql
  namespace: {{ .Values.metadata.namespace }}
spec: 
  replicas: {{ .Values.spec.replicas }}
  selector: 
    matchLabels: 
      app: mysql
  template: 
    metadata: 
      labels: 
        app: mysql
        name: mysql
        version: latest
    spec: 
      containers: 
        - 
          env: 
            - 
              name: MYSQL_ROOT_PASSWORD
              value: {{ .Values.env.password }}
            - 
              name: MYSQL_DATABASE
              value: {{ .Values.env.db }}
          image: "mariadb:latest"
          name: mysql
          volumeMounts: 
            - 
              mountPath: /var/lib/mysql
              name: db-folder
            -   
              mountPath: /etc/mysql/conf.d
              name: config-volume
            
              
      {{- if .Values.nodeSelector.enable }}
      nodeSelector: 
        name: {{ .Values.nodeSelector.label }}
      {{- end }}
      volumes: 
        - 
          name: db-folder
          persistentVolumeClaim: 
            claimName: {{ .Values.valume.pvc }}
        - 
          name: config-volume
          configMap:
            name: mariadb-config
            optional: true  

