apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.valume.pv }}
  namespace: {{ .Values.metadata.namespace }}
  labels:
    type: local
    label-name: mysql
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.valume.path }}
