apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: {{ .Values.metadata.namespace }}
spec:
  type:  {{ .Values.service.type }}
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
    nodePort : {{ .Values.service.nodeport }}
  selector:
    app: mysql
