---
# tasks file for jenkins_role

- name: Install JDKs
  become: yes
  become_method: sudo
  become_user: "{{ sudo_user }}"
  yum:
    name:
      - java-1.8.0-openjdk-devel
      - java-1.8.0-openjdk
    state: present

- name: Download jenkins repo & save it in local
  become: yes
  become_method: sudo
  become_user: "{{ sudo_user }}"
  get_url:
    url: "{{ jenkins_url }}"
    dest: /etc/yum.repos.d/jenkins.repo
    mode: "755"

- name: Import key to access repo locally
  become: yes
  become_method: sudo
  become_user: "{{ sudo_user }}"
  rpm_key:
  state: present
  key: http://pkg.jenkins.io/redhat-stable/jenkins.io.key

- name: Install Jenkins
  become: yes
  become_method: sudo
  become_user: "{{ sudo_user }}"
  yum:
    name:
      - jenkins

- name: Restart jenkins service
  become: yes
  become_method: sudo
  become_user: "{{ sudo_user }}"
  systemd:
    name: jenkins
    state: restarted

- name: Enable jenkins service
  become: yes
  become_method: sudo
  become_user: "{{ sudo_user }}"
  systemd:
    name: jenkins
    enabled: yes