---
# tasks file for rke_role

- name: Install EPEL repo
  yum:
     name: epel-release
     state: present

- name: Install the latest version of pip
  yum:
    name: python*-pip
    state: latest

- name: Check if docker is installed
  pip:
    name: docker
    state: present

- name: Download Rancher rke_linux-amd64 to bin location
  get_url:
    url: https://github.com/rancher/rke/releases/download/v0.2.1/rke_linux-amd64
    dest: /usr/local/bin/rke
    mode: '0755'
  register: rke_binary

- name: Check if Rancher has been installed
  command: rke --version

- name: Create target directory for cluster.yaml
  file: path="{{ role_path }}/files/" state=directory mode=0777

- name: Render jinja template to create cluster.yaml
  template:
    src: cluster.j2
    dest: "{{ role_path }}/files/cluster.yaml"
    mode: '0777'
  register: rke_cluster_config

- name: Run RKE installer
  shell: |
    rke up | tee /var/log/rke-up.log
  args:
    chdir: "{{ role_path }}/files/"
  when: rke_binary is changed or rke_cluster_config is changed or rke_force_configure

- name: Install kubectl
  get_url:
    url: "{{ kubectl_url }}"
    dest: /usr/local/bin/kubectl
    mode: "755"

- name: Ensure $HOME/.kube exists
  file:
    path: "{{ ansible_env.HOME }}/.kube"
    state: directory

- name: Copy kubeconfig to default location
  copy:
    remote_src: yes
    src: "{{ role_path }}/files/kube_config_cluster.yml"
    dest: "{{ ansible_env.HOME }}/.kube/config"