apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "cassandra.fullname" . }}-headless
  labels: {{- include "cassandra.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels: {{- include "cassandra.matchLabels" . | nindent 6 }}
  {{- if .Values.minAvailable }}
  minAvailable: {{ .Values.cluster.minimumAvailable }}
  {{- else }}
  maxUnavailable: 1
  {{- end }}
