kind: PersistentVolume
apiVersion: v1
metadata:
  name: cassandra-pv
  labels:
    type: cassandra-data
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/.data/cassandra"